name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install composer dependencies
      run: composer install

    - name: Install node dependencies
      run: npm install

    - name: Gulp
      run: gulp

